language: node_js
node_js:
  - "12"

sudo: false

install:
  - npm install typescript -g
  - npm install ts-node -g
  - npm install tslint -g  
  - npm install
script:
  - npm run lint
  - npm run test
